/**
 * github.ts — read-only accessor for the committed GitHub cache (PRD §7.4).
 *
 * This module reads `data/github-cache.json`, which is generated by
 * `scripts/sync-github.ts` and COMMITTED to the repository. That is what makes
 * `pnpm build` work with no network access (AC-16.1) and what keeps a GitHub
 * outage from ever being a portfolio outage.
 *
 * Nothing here talks to the network. There is no token in this file, and there
 * must never be one — the token exists only in CI (PRD §5.7).
 */
import "server-only";

import fs from "node:fs";
import path from "node:path";

import { GitHubCacheSchema, type GitHubCache, type RepoData } from "./schemas";

const CACHE_PATH = path.join(process.cwd(), "data", "github-cache.json");

const EMPTY_CACHE: GitHubCache = {
  version: 1,
  syncedAt: new Date(0).toISOString(),
  repos: {},
};

let cache: GitHubCache | null = null;

function loadCache(): GitHubCache {
  if (cache) return cache;

  if (!fs.existsSync(CACHE_PATH)) {
    // A missing cache is survivable: every evidence block degrades to absent.
    // It is not an error, because a fresh clone has not run sync yet.
    cache = EMPTY_CACHE;
    return cache;
  }

  const parsed = GitHubCacheSchema.safeParse(
    JSON.parse(fs.readFileSync(CACHE_PATH, "utf8")),
  );

  if (!parsed.success) {
    // A malformed cache IS an error — it means sync wrote something bad, and
    // silently rendering an empty site would hide that.
    throw new Error(
      `data/github-cache.json failed validation. Re-run \`pnpm sync:github\`.\n${parsed.error.issues
        .map((i) => `  - ${i.path.join(".")}: ${i.message}`)
        .join("\n")}`,
    );
  }

  cache = parsed.data;
  return cache;
}

/**
 * Null-safe by design (AC-05.4). A private, renamed, deleted, or never-synced
 * repository returns null and the caller omits the evidence block entirely
 * rather than rendering an error.
 */
export function getRepoData(nameWithOwner: string | undefined): RepoData | null {
  if (!nameWithOwner) return null;
  const repo = loadCache().repos[nameWithOwner];
  if (!repo) return null;
  // A repository that has gone private must not leak its old cached numbers.
  if (repo.isPrivate) return null;
  return repo;
}

export function getCacheAge(): { syncedAt: string; days: number } {
  const { syncedAt } = loadCache();
  const days = Math.floor((Date.now() - Date.parse(syncedAt)) / 86_400_000);
  return { syncedAt, days };
}

/* ── Presentation helpers ────────────────────────────────────────────────── */

/**
 * AC-05.6: vanity metrics are not inflated. A "0 ★" badge is worse than no
 * badge, so anything at or below 2 is simply not shown.
 */
export const STAR_DISPLAY_THRESHOLD = 2;

export function shouldShowStars(repo: RepoData): boolean {
  return repo.stars > STAR_DISPLAY_THRESHOLD;
}

export function shouldShowForks(repo: RepoData): boolean {
  return repo.forks > STAR_DISPLAY_THRESHOLD;
}

/** Whole years and months since the first commit, for "repository age". */
export function repoAge(repo: RepoData): string {
  const months = Math.max(
    0,
    Math.floor((Date.now() - Date.parse(repo.createdAt)) / (30.44 * 86_400_000)),
  );
  const years = Math.floor(months / 12);
  const rem = months % 12;
  if (years === 0) return `${months} month${months === 1 ? "" : "s"}`;
  if (rem === 0) return `${years} year${years === 1 ? "" : "s"}`;
  return `${years}y ${rem}m`;
}

/**
 * Languages worth rendering. Anything under 1% is noise in a bar chart and
 * lengthens the legend for no information gain.
 */
export function significantLanguages(
  repo: RepoData,
  minPercent = 1,
): RepoData["languages"] {
  return repo.languages.filter((l) => l.percent >= minPercent);
}
